-- Generated by demand_metrics.py; run against /workspace/hackathon-data/cache/bank.duckdb (read-only)

CREATE OR REPLACE TEMP VIEW tx AS
SELECT t.*, c.country, c.segment, date_trunc('month', t.transaction_date)::DATE AS ym,
       (t.transaction_status='Pending')  AS is_pending,
       (t.transaction_status='Reversed') AS is_reversed,
       (t.fraud_score > 30)              AS is_hi_fs,
       CASE WHEN t.fraud_score > 30              THEN '1 HIGH'
            WHEN t.transaction_status='Pending'  THEN '2 Pending'
            WHEN t.transaction_status='Reversed' THEN '3 Reversed'
            ELSE '4 Other' END AS case_bucket
FROM transactions t JOIN customers c USING (customer_id);

CREATE OR REPLACE TEMP VIEW cp AS
SELECT k.*, c.country, c.segment, date_trunc('month', k.creation_date)::DATE AS ym,
       (k.category='Transactions') AS dispute_narrow,
       (k.category IN ('Transactions','Fees')) AS dispute_broad,
       CASE WHEN k.category='Transactions' THEN 'Transactions (Cargo no reconocido)'
            WHEN k.category='Fees' THEN 'Fees (Cobro indebido)' ELSE 'Other categories' END AS cat_group,
       (k.status IN ('Resolved','Closed','Rejected')) AS is_final,
       CASE WHEN COALESCE(k.resolution_date,k.closing_date) IS NOT NULL
            THEN date_diff('second', k.creation_date, COALESCE(k.resolution_date,k.closing_date))/86400.0 END AS res_days_ts
FROM complaints k JOIN customers c USING (customer_id);


-- tx_overall  -> out/tx_overall.csv
SELECT 
  count(*) AS transactions,
  count(*) FILTER (is_pending) AS pending, round(100.0*avg(is_pending::INT),3) AS pending_pct,
  count(*) FILTER (is_reversed) AS reversed, round(100.0*avg(is_reversed::INT),3) AS reversed_pct,
  count(*) FILTER (is_pending OR is_reversed) AS pending_or_reversed,
  round(100.0*avg((is_pending OR is_reversed)::INT),3) AS pending_or_reversed_pct,
  count(*) FILTER (transaction_status='Declined') AS declined,
  count(fraud_score) AS fraud_score_nonnull,
  count(*) FILTER (is_hi_fs) AS fs_gt30, round(100.0*count(*) FILTER (is_hi_fs)/count(*),4) AS fs_gt30_pct_all,
  round(100.0*count(*) FILTER (is_hi_fs)/count(fraud_score),4) AS fs_gt30_pct_scored,
  count(*) FILTER (is_hi_fs AND NOT is_pending AND NOT is_reversed) AS fs_gt30_excl_pend_rev,
  count(*) FILTER (is_fraud) AS is_fraud, round(100.0*avg(is_fraud::INT),4) AS is_fraud_pct,
  count(*) FILTER (is_fraud AND is_hi_fs) AS is_fraud_and_fs_gt30
 FROM tx;

-- tx_by_country  -> out/tx_by_country.csv
SELECT country, 
  count(*) AS transactions,
  count(*) FILTER (is_pending) AS pending, round(100.0*avg(is_pending::INT),3) AS pending_pct,
  count(*) FILTER (is_reversed) AS reversed, round(100.0*avg(is_reversed::INT),3) AS reversed_pct,
  count(*) FILTER (is_pending OR is_reversed) AS pending_or_reversed,
  round(100.0*avg((is_pending OR is_reversed)::INT),3) AS pending_or_reversed_pct,
  count(*) FILTER (transaction_status='Declined') AS declined,
  count(fraud_score) AS fraud_score_nonnull,
  count(*) FILTER (is_hi_fs) AS fs_gt30, round(100.0*count(*) FILTER (is_hi_fs)/count(*),4) AS fs_gt30_pct_all,
  round(100.0*count(*) FILTER (is_hi_fs)/count(fraud_score),4) AS fs_gt30_pct_scored,
  count(*) FILTER (is_hi_fs AND NOT is_pending AND NOT is_reversed) AS fs_gt30_excl_pend_rev,
  count(*) FILTER (is_fraud) AS is_fraud, round(100.0*avg(is_fraud::INT),4) AS is_fraud_pct,
  count(*) FILTER (is_fraud AND is_hi_fs) AS is_fraud_and_fs_gt30
 FROM tx GROUP BY 1 ORDER BY 2 DESC;

-- tx_by_segment  -> out/tx_by_segment.csv
SELECT segment, 
  count(*) AS transactions,
  count(*) FILTER (is_pending) AS pending, round(100.0*avg(is_pending::INT),3) AS pending_pct,
  count(*) FILTER (is_reversed) AS reversed, round(100.0*avg(is_reversed::INT),3) AS reversed_pct,
  count(*) FILTER (is_pending OR is_reversed) AS pending_or_reversed,
  round(100.0*avg((is_pending OR is_reversed)::INT),3) AS pending_or_reversed_pct,
  count(*) FILTER (transaction_status='Declined') AS declined,
  count(fraud_score) AS fraud_score_nonnull,
  count(*) FILTER (is_hi_fs) AS fs_gt30, round(100.0*count(*) FILTER (is_hi_fs)/count(*),4) AS fs_gt30_pct_all,
  round(100.0*count(*) FILTER (is_hi_fs)/count(fraud_score),4) AS fs_gt30_pct_scored,
  count(*) FILTER (is_hi_fs AND NOT is_pending AND NOT is_reversed) AS fs_gt30_excl_pend_rev,
  count(*) FILTER (is_fraud) AS is_fraud, round(100.0*avg(is_fraud::INT),4) AS is_fraud_pct,
  count(*) FILTER (is_fraud AND is_hi_fs) AS is_fraud_and_fs_gt30
 FROM tx GROUP BY 1 ORDER BY 2 DESC;

-- tx_by_country_segment  -> out/tx_by_country_segment.csv
SELECT country, segment, 
  count(*) AS transactions,
  count(*) FILTER (is_pending) AS pending, round(100.0*avg(is_pending::INT),3) AS pending_pct,
  count(*) FILTER (is_reversed) AS reversed, round(100.0*avg(is_reversed::INT),3) AS reversed_pct,
  count(*) FILTER (is_pending OR is_reversed) AS pending_or_reversed,
  round(100.0*avg((is_pending OR is_reversed)::INT),3) AS pending_or_reversed_pct,
  count(*) FILTER (transaction_status='Declined') AS declined,
  count(fraud_score) AS fraud_score_nonnull,
  count(*) FILTER (is_hi_fs) AS fs_gt30, round(100.0*count(*) FILTER (is_hi_fs)/count(*),4) AS fs_gt30_pct_all,
  round(100.0*count(*) FILTER (is_hi_fs)/count(fraud_score),4) AS fs_gt30_pct_scored,
  count(*) FILTER (is_hi_fs AND NOT is_pending AND NOT is_reversed) AS fs_gt30_excl_pend_rev,
  count(*) FILTER (is_fraud) AS is_fraud, round(100.0*avg(is_fraud::INT),4) AS is_fraud_pct,
  count(*) FILTER (is_fraud AND is_hi_fs) AS is_fraud_and_fs_gt30
 FROM tx GROUP BY 1,2 ORDER BY 1,2;

-- tx_by_month  -> out/tx_by_month.csv
SELECT ym AS month, 
  count(*) AS transactions,
  count(*) FILTER (is_pending) AS pending, round(100.0*avg(is_pending::INT),3) AS pending_pct,
  count(*) FILTER (is_reversed) AS reversed, round(100.0*avg(is_reversed::INT),3) AS reversed_pct,
  count(*) FILTER (is_pending OR is_reversed) AS pending_or_reversed,
  round(100.0*avg((is_pending OR is_reversed)::INT),3) AS pending_or_reversed_pct,
  count(*) FILTER (transaction_status='Declined') AS declined,
  count(fraud_score) AS fraud_score_nonnull,
  count(*) FILTER (is_hi_fs) AS fs_gt30, round(100.0*count(*) FILTER (is_hi_fs)/count(*),4) AS fs_gt30_pct_all,
  round(100.0*count(*) FILTER (is_hi_fs)/count(fraud_score),4) AS fs_gt30_pct_scored,
  count(*) FILTER (is_hi_fs AND NOT is_pending AND NOT is_reversed) AS fs_gt30_excl_pend_rev,
  count(*) FILTER (is_fraud) AS is_fraud, round(100.0*avg(is_fraud::INT),4) AS is_fraud_pct,
  count(*) FILTER (is_fraud AND is_hi_fs) AS is_fraud_and_fs_gt30
 FROM tx GROUP BY 1 ORDER BY 1;

-- tx_status_by_is_fraud  -> out/tx_status_by_is_fraud.csv
SELECT transaction_status, count(*) n, count(fraud_score) scored,
  count(*) FILTER (is_hi_fs) fs_gt30, count(*) FILTER (is_fraud) is_fraud FROM tx GROUP BY 1 ORDER BY 2 DESC;

-- tx_case_mix  -> out/tx_case_mix.csv
SELECT case_bucket, count(*) n, round(100.0*count(*)/sum(count(*)) OVER (),3) pct,
  count(*) FILTER (is_fraud) is_fraud FROM tx GROUP BY 1 ORDER BY 1;

-- tx_case_mix_by_country  -> out/tx_case_mix_by_country.csv
SELECT country, case_bucket, count(*) n,
  round(100.0*count(*)/sum(count(*)) OVER (PARTITION BY country),3) pct FROM tx GROUP BY 1,2 ORDER BY 1,2;

-- tx_by_transaction_country_raw  -> out/tx_by_transaction_country_raw.csv
SELECT transaction_country, count(*) n FROM transactions GROUP BY 1 ORDER BY 2 DESC;

-- cp_categories  -> out/cp_categories.csv
SELECT category, subcategory, count(*) n, round(100.0*count(*)/sum(count(*)) OVER (),2) pct
  FROM cp GROUP BY 1,2 ORDER BY 1,3 DESC;

-- cp_case_type_by_group  -> out/cp_case_type_by_group.csv
SELECT cat_group, case_type, count(*) n FROM cp GROUP BY 1,2 ORDER BY 1,3 DESC;

-- cp_overall  -> out/cp_overall.csv
SELECT 
  count(*) AS complaints,
  count(*) FILTER (dispute_narrow) AS dispute_narrow, round(100.0*avg(dispute_narrow::INT),2) AS dispute_narrow_pct,
  count(*) FILTER (dispute_broad) AS dispute_broad, round(100.0*avg(dispute_broad::INT),2) AS dispute_broad_pct
 FROM cp;

-- cp_by_country  -> out/cp_by_country.csv
SELECT country, 
  count(*) AS complaints,
  count(*) FILTER (dispute_narrow) AS dispute_narrow, round(100.0*avg(dispute_narrow::INT),2) AS dispute_narrow_pct,
  count(*) FILTER (dispute_broad) AS dispute_broad, round(100.0*avg(dispute_broad::INT),2) AS dispute_broad_pct
 FROM cp GROUP BY 1 ORDER BY 2 DESC;

-- cp_by_segment  -> out/cp_by_segment.csv
SELECT segment, 
  count(*) AS complaints,
  count(*) FILTER (dispute_narrow) AS dispute_narrow, round(100.0*avg(dispute_narrow::INT),2) AS dispute_narrow_pct,
  count(*) FILTER (dispute_broad) AS dispute_broad, round(100.0*avg(dispute_broad::INT),2) AS dispute_broad_pct
 FROM cp GROUP BY 1 ORDER BY 2 DESC;

-- cp_by_country_segment  -> out/cp_by_country_segment.csv
SELECT country, segment, 
  count(*) AS complaints,
  count(*) FILTER (dispute_narrow) AS dispute_narrow, round(100.0*avg(dispute_narrow::INT),2) AS dispute_narrow_pct,
  count(*) FILTER (dispute_broad) AS dispute_broad, round(100.0*avg(dispute_broad::INT),2) AS dispute_broad_pct
 FROM cp GROUP BY 1,2 ORDER BY 1,2;

-- cp_by_month  -> out/cp_by_month.csv
SELECT ym AS month, 
  count(*) AS complaints,
  count(*) FILTER (dispute_narrow) AS dispute_narrow, round(100.0*avg(dispute_narrow::INT),2) AS dispute_narrow_pct,
  count(*) FILTER (dispute_broad) AS dispute_broad, round(100.0*avg(dispute_broad::INT),2) AS dispute_broad_pct
,
  count(*) FILTER (category='Fees') AS fees, count(*) FILTER (NOT dispute_broad) AS other_categories
  FROM cp GROUP BY 1 ORDER BY 1;

-- cp_by_channel_group  -> out/cp_by_channel_group.csv
SELECT reception_channel, cat_group, count(*) n FROM cp GROUP BY 1,2 ORDER BY 1,2;

-- res_overall  -> out/res_overall.csv
SELECT 
  count(*) AS complaints,
  count(*) FILTER (is_final) AS final_status, round(100.0*avg(is_final::INT),2) AS final_pct,
  count(*) FILTER (status='Resolved') AS resolved, count(*) FILTER (status='Closed') AS closed,
  count(*) FILTER (status='Rejected') AS rejected, count(*) FILTER (status='Open') AS open,
  count(*) FILTER (status='In Process') AS in_process, count(*) FILTER (status='Escalated') AS escalated,
  count(res_days_ts) AS n_with_open_and_close_ts,
  round(quantile_cont(res_days_ts,0.5),2) AS res_days_p50, round(quantile_cont(res_days_ts,0.75),2) AS res_days_p75,
  round(quantile_cont(res_days_ts,0.9),2) AS res_days_p90, round(avg(res_days_ts),2) AS res_days_mean,
  round(quantile_cont(resolution_days,0.5),1) AS col_resolution_days_p50,
  round(quantile_cont(resolution_days,0.75),1) AS col_resolution_days_p75,
  round(quantile_cont(resolution_days,0.9),1) AS col_resolution_days_p90,
  count(*) FILTER (sla_breached) AS sla_breached, round(100.0*avg(sla_breached::INT),2) AS sla_breach_pct_all,
  count(*) FILTER (sla_breached AND is_final) AS sla_breached_final,
  round(100.0*count(*) FILTER (sla_breached AND is_final)/NULLIF(count(*) FILTER (is_final),0),2) AS sla_breach_pct_final
 FROM cp;

-- res_by_cat_group  -> out/res_by_cat_group.csv
SELECT cat_group, 
  count(*) AS complaints,
  count(*) FILTER (is_final) AS final_status, round(100.0*avg(is_final::INT),2) AS final_pct,
  count(*) FILTER (status='Resolved') AS resolved, count(*) FILTER (status='Closed') AS closed,
  count(*) FILTER (status='Rejected') AS rejected, count(*) FILTER (status='Open') AS open,
  count(*) FILTER (status='In Process') AS in_process, count(*) FILTER (status='Escalated') AS escalated,
  count(res_days_ts) AS n_with_open_and_close_ts,
  round(quantile_cont(res_days_ts,0.5),2) AS res_days_p50, round(quantile_cont(res_days_ts,0.75),2) AS res_days_p75,
  round(quantile_cont(res_days_ts,0.9),2) AS res_days_p90, round(avg(res_days_ts),2) AS res_days_mean,
  round(quantile_cont(resolution_days,0.5),1) AS col_resolution_days_p50,
  round(quantile_cont(resolution_days,0.75),1) AS col_resolution_days_p75,
  round(quantile_cont(resolution_days,0.9),1) AS col_resolution_days_p90,
  count(*) FILTER (sla_breached) AS sla_breached, round(100.0*avg(sla_breached::INT),2) AS sla_breach_pct_all,
  count(*) FILTER (sla_breached AND is_final) AS sla_breached_final,
  round(100.0*count(*) FILTER (sla_breached AND is_final)/NULLIF(count(*) FILTER (is_final),0),2) AS sla_breach_pct_final
 FROM cp GROUP BY 1 ORDER BY 1;

-- res_by_country  -> out/res_by_country.csv
SELECT country, 
  count(*) AS complaints,
  count(*) FILTER (is_final) AS final_status, round(100.0*avg(is_final::INT),2) AS final_pct,
  count(*) FILTER (status='Resolved') AS resolved, count(*) FILTER (status='Closed') AS closed,
  count(*) FILTER (status='Rejected') AS rejected, count(*) FILTER (status='Open') AS open,
  count(*) FILTER (status='In Process') AS in_process, count(*) FILTER (status='Escalated') AS escalated,
  count(res_days_ts) AS n_with_open_and_close_ts,
  round(quantile_cont(res_days_ts,0.5),2) AS res_days_p50, round(quantile_cont(res_days_ts,0.75),2) AS res_days_p75,
  round(quantile_cont(res_days_ts,0.9),2) AS res_days_p90, round(avg(res_days_ts),2) AS res_days_mean,
  round(quantile_cont(resolution_days,0.5),1) AS col_resolution_days_p50,
  round(quantile_cont(resolution_days,0.75),1) AS col_resolution_days_p75,
  round(quantile_cont(resolution_days,0.9),1) AS col_resolution_days_p90,
  count(*) FILTER (sla_breached) AS sla_breached, round(100.0*avg(sla_breached::INT),2) AS sla_breach_pct_all,
  count(*) FILTER (sla_breached AND is_final) AS sla_breached_final,
  round(100.0*count(*) FILTER (sla_breached AND is_final)/NULLIF(count(*) FILTER (is_final),0),2) AS sla_breach_pct_final
 FROM cp GROUP BY 1 ORDER BY 2 DESC;

-- res_by_segment  -> out/res_by_segment.csv
SELECT segment, 
  count(*) AS complaints,
  count(*) FILTER (is_final) AS final_status, round(100.0*avg(is_final::INT),2) AS final_pct,
  count(*) FILTER (status='Resolved') AS resolved, count(*) FILTER (status='Closed') AS closed,
  count(*) FILTER (status='Rejected') AS rejected, count(*) FILTER (status='Open') AS open,
  count(*) FILTER (status='In Process') AS in_process, count(*) FILTER (status='Escalated') AS escalated,
  count(res_days_ts) AS n_with_open_and_close_ts,
  round(quantile_cont(res_days_ts,0.5),2) AS res_days_p50, round(quantile_cont(res_days_ts,0.75),2) AS res_days_p75,
  round(quantile_cont(res_days_ts,0.9),2) AS res_days_p90, round(avg(res_days_ts),2) AS res_days_mean,
  round(quantile_cont(resolution_days,0.5),1) AS col_resolution_days_p50,
  round(quantile_cont(resolution_days,0.75),1) AS col_resolution_days_p75,
  round(quantile_cont(resolution_days,0.9),1) AS col_resolution_days_p90,
  count(*) FILTER (sla_breached) AS sla_breached, round(100.0*avg(sla_breached::INT),2) AS sla_breach_pct_all,
  count(*) FILTER (sla_breached AND is_final) AS sla_breached_final,
  round(100.0*count(*) FILTER (sla_breached AND is_final)/NULLIF(count(*) FILTER (is_final),0),2) AS sla_breach_pct_final
 FROM cp GROUP BY 1 ORDER BY 2 DESC;

-- res_disputes_by_country  -> out/res_disputes_by_country.csv
SELECT country, 
  count(*) AS complaints,
  count(*) FILTER (is_final) AS final_status, round(100.0*avg(is_final::INT),2) AS final_pct,
  count(*) FILTER (status='Resolved') AS resolved, count(*) FILTER (status='Closed') AS closed,
  count(*) FILTER (status='Rejected') AS rejected, count(*) FILTER (status='Open') AS open,
  count(*) FILTER (status='In Process') AS in_process, count(*) FILTER (status='Escalated') AS escalated,
  count(res_days_ts) AS n_with_open_and_close_ts,
  round(quantile_cont(res_days_ts,0.5),2) AS res_days_p50, round(quantile_cont(res_days_ts,0.75),2) AS res_days_p75,
  round(quantile_cont(res_days_ts,0.9),2) AS res_days_p90, round(avg(res_days_ts),2) AS res_days_mean,
  round(quantile_cont(resolution_days,0.5),1) AS col_resolution_days_p50,
  round(quantile_cont(resolution_days,0.75),1) AS col_resolution_days_p75,
  round(quantile_cont(resolution_days,0.9),1) AS col_resolution_days_p90,
  count(*) FILTER (sla_breached) AS sla_breached, round(100.0*avg(sla_breached::INT),2) AS sla_breach_pct_all,
  count(*) FILTER (sla_breached AND is_final) AS sla_breached_final,
  round(100.0*count(*) FILTER (sla_breached AND is_final)/NULLIF(count(*) FILTER (is_final),0),2) AS sla_breach_pct_final
 FROM cp WHERE dispute_narrow GROUP BY 1 ORDER BY 2 DESC;

-- res_by_priority  -> out/res_by_priority.csv
SELECT priority, 
  count(*) AS complaints,
  count(*) FILTER (is_final) AS final_status, round(100.0*avg(is_final::INT),2) AS final_pct,
  count(*) FILTER (status='Resolved') AS resolved, count(*) FILTER (status='Closed') AS closed,
  count(*) FILTER (status='Rejected') AS rejected, count(*) FILTER (status='Open') AS open,
  count(*) FILTER (status='In Process') AS in_process, count(*) FILTER (status='Escalated') AS escalated,
  count(res_days_ts) AS n_with_open_and_close_ts,
  round(quantile_cont(res_days_ts,0.5),2) AS res_days_p50, round(quantile_cont(res_days_ts,0.75),2) AS res_days_p75,
  round(quantile_cont(res_days_ts,0.9),2) AS res_days_p90, round(avg(res_days_ts),2) AS res_days_mean,
  round(quantile_cont(resolution_days,0.5),1) AS col_resolution_days_p50,
  round(quantile_cont(resolution_days,0.75),1) AS col_resolution_days_p75,
  round(quantile_cont(resolution_days,0.9),1) AS col_resolution_days_p90,
  count(*) FILTER (sla_breached) AS sla_breached, round(100.0*avg(sla_breached::INT),2) AS sla_breach_pct_all,
  count(*) FILTER (sla_breached AND is_final) AS sla_breached_final,
  round(100.0*count(*) FILTER (sla_breached AND is_final)/NULLIF(count(*) FILTER (is_final),0),2) AS sla_breach_pct_final
 FROM cp GROUP BY 1 ORDER BY 2 DESC;

-- res_status_mix  -> out/res_status_mix.csv
SELECT cat_group, status, count(*) n,
  round(100.0*count(*)/sum(count(*)) OVER (PARTITION BY cat_group),2) pct,
  count(res_days_ts) n_with_dates, count(*) FILTER (sla_breached) sla_breached
  FROM cp GROUP BY 1,2 ORDER BY 1,3 DESC;

-- res_days_hist  -> out/res_days_hist.csv
SELECT cat_group, CAST(floor(res_days_ts) AS INT) AS day_floor, count(*) n
  FROM cp WHERE res_days_ts IS NOT NULL GROUP BY 1,2 ORDER BY 1,2;

-- res_check_ts_vs_column  -> out/res_check_ts_vs_column.csv
SELECT count(*) FILTER (res_days_ts IS NOT NULL) n_ts, count(resolution_days) n_col,
  count(*) FILTER (res_days_ts IS NOT NULL AND resolution_days IS NOT NULL AND abs(res_days_ts-resolution_days)>1) n_diff_gt1d
  FROM cp;

-- res_sla_vs_days  -> out/res_sla_vs_days.csv
SELECT sla_breached, count(*) n, count(res_days_ts) n_dates,
  round(quantile_cont(res_days_ts,0.5),2) p50, round(quantile_cont(res_days_ts,0.9),2) p90 FROM cp GROUP BY 1;

-- cost_columns_scan  -> out/cost_columns_scan.csv
SELECT table_name, column_name, data_type FROM information_schema.columns
  WHERE table_name NOT IN ('tx','cp') AND regexp_matches(lower(column_name),'cost|price|fee|salary|wage|amount|compens|duration|handl|effort|budget|value|time_seconds')
  ORDER BY 1,2;

-- cost_compensation_by_group  -> out/cost_compensation_by_group.csv
SELECT cat_group, COALESCE(currency,'(null)') currency, count(*) complaints,
  count(compensation_granted) n_comp, count(*) FILTER (compensation_granted>0) n_comp_gt0,
  round(sum(compensation_granted),2) sum_comp, round(median(compensation_granted),2) median_comp
  FROM cp GROUP BY 1,2 ORDER BY 1,2;

-- cost_callcenter_handle_time  -> out/cost_callcenter_handle_time.csv
SELECT reason_category, count(*) interactions, count(duration_seconds) n_duration,
  round(avg(duration_seconds),1) aht_sec_mean, round(median(duration_seconds),1) aht_sec_p50,
  round(avg(wait_time_seconds),1) wait_sec_mean, round(100*avg(was_resolved::INT),2) resolved_pct,
  round(100*avg(was_escalated::INT),2) escalated_pct, round(100*avg(requires_followup::INT),2) followup_pct
  FROM call_center_interactions GROUP BY 1 ORDER BY 2 DESC;

-- cost_callcenter_transaccional_by_country_segment  -> out/cost_callcenter_transaccional_by_country_segment.csv
SELECT c.country, c.segment, count(*) interactions,
  round(avg(i.duration_seconds),1) aht_sec_mean, round(100*avg(i.was_resolved::INT),2) resolved_pct
  FROM call_center_interactions i JOIN customers c USING (customer_id)
  WHERE i.reason_category='Transaccional' GROUP BY 1,2 ORDER BY 1,2;

-- cost_callcenter_by_channel_transaccional  -> out/cost_callcenter_by_channel_transaccional.csv
SELECT channel, count(*) interactions, round(avg(duration_seconds),1) aht_sec_mean,
  round(100*avg(was_resolved::INT),2) resolved_pct FROM call_center_interactions
  WHERE reason_category='Transaccional' GROUP BY 1 ORDER BY 2 DESC;
