# ruff: noqa: E501
"""Explicit schema contract for silver. Bronze columns must match exactly (names + order-insensitive set); every non-null
bronze value must cast to the contract type; enumerations and ranges are enforced. Any violation raises ContractError."""


class ContractError(Exception):
    pass


CONTRACT = {
    "transactions": {
        "pk": ["transaction_id"],
        "columns": {
            "transaction_id": "VARCHAR",
            "transaction_date": "TIMESTAMP",
            "process_date": "DATE",
            "product_id": "VARCHAR",
            "customer_id": "VARCHAR",
            "transaction_type": "VARCHAR",
            "transaction_category": "VARCHAR",
            "amount": "DECIMAL(15,2)",
            "currency": "VARCHAR",
            "amount_usd": "DECIMAL(15,2)",
            "channel": "VARCHAR",
            "branch_id": "VARCHAR",
            "merchant_name": "VARCHAR",
            "merchant_category": "VARCHAR",
            "transaction_country": "VARCHAR",
            "transaction_city": "VARCHAR",
            "transaction_status": "VARCHAR",
            "response_code": "VARCHAR",
            "is_fraud": "BOOLEAN",
            "fraud_score": "DECIMAL(5,2)",
            "latitude": "DECIMAL(10,7)",
            "longitude": "DECIMAL(10,7)",
        },
        "not_null": [
            "transaction_id",
            "transaction_date",
            "process_date",
            "product_id",
            "customer_id",
            "amount",
            "currency",
            "channel",
            "transaction_country",
            "transaction_status",
            "is_fraud",
        ],
        "enums": {
            "transaction_status": ["Approved", "Declined", "Pending", "Reversed"],
            "currency": ["MXN", "COP", "ARS", "USD"],
            "channel": ["ATM", "Branch", "Web", "App", "POS", "Transfer"],
            "transaction_type": [
                "Deposit",
                "Withdrawal",
                "Transfer",
                "Payment",
                "Purchase",
                "Adjustment",
            ],
        },
        "ranges": {"fraud_score": (0, 100)},
    },
    "customers": {
        "pk": ["customer_id"],
        "columns": {
            "customer_id": "VARCHAR",
            "document_number": "VARCHAR",
            "document_type": "VARCHAR",
            "first_name": "VARCHAR",
            "last_name": "VARCHAR",
            "date_of_birth": "DATE",
            "gender": "VARCHAR",
            "email": "VARCHAR",
            "mobile_phone": "VARCHAR",
            "landline_phone": "VARCHAR",
            "address": "VARCHAR",
            "city": "VARCHAR",
            "state": "VARCHAR",
            "country": "VARCHAR",
            "postal_code": "VARCHAR",
            "detected_accent": "VARCHAR",
            "segment": "VARCHAR",
            "credit_score": "INTEGER",
            "estimated_monthly_income": "DECIMAL(12,2)",
            "occupation": "VARCHAR",
            "marital_status": "VARCHAR",
            "education_level": "VARCHAR",
            "registration_date": "TIMESTAMP",
            "registration_branch_id": "VARCHAR",
            "customer_status": "VARCHAR",
            "last_updated": "TIMESTAMP",
            "accepts_marketing": "BOOLEAN",
        },
        "not_null": ["customer_id", "country", "segment", "registration_date"],
        "enums": {
            "segment": ["Premium", "Plus", "Basic", "Student"],
            "country": ["Mexico", "Colombia", "Argentina"],
        },
        "ranges": {"credit_score": (300, 850)},
    },
    "products": {
        "pk": ["product_id"],
        "columns": {
            "product_id": "VARCHAR",
            "customer_id": "VARCHAR",
            "product_type": "VARCHAR",
            "product_number": "VARCHAR",
            "currency": "VARCHAR",
            "current_balance": "DECIMAL(15,2)",
            "credit_limit": "DECIMAL(15,2)",
            "interest_rate": "DECIMAL(5,2)",
            "opening_date": "DATE",
            "expiration_date": "DATE",
            "opening_branch_id": "VARCHAR",
            "product_status": "VARCHAR",
            "opening_channel": "VARCHAR",
            "has_linked_app": "BOOLEAN",
            "days_past_due": "INTEGER",
            "last_transaction_date": "TIMESTAMP",
            "last_updated": "TIMESTAMP",
        },
        "not_null": ["product_id", "customer_id", "product_type", "opening_date"],
        "enums": {},
        "ranges": {},
    },
}

# value normalization applied in silver (before enum checks)
COUNTRY_MAP = {
    "México": "Mexico",
    "Mexico": "Mexico",
    "Colombia": "Colombia",
    "Argentina": "Argentina",
    "Brazil": "Brazil",
    "Spain": "Spain",
    "USA": "USA",
}
COUNTRY_COLUMNS = {"transactions": ["transaction_country"], "customers": ["country"]}
